version: "3.1"
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: testdb
        volumes:
            - ./data/db:/var/lib/postgresql/data
    app:
        build: ./app
        depends_on:
            - db
        ports:
            - 8080:8080
        links:
            - db
        environment:
            PG_HOST: db
            PG_PORT: 5432
            PG_DB: testdb
            PG_PASS: password
            PG_USER: user
            TOKEN_PASS: abcdefasdfasdfasdf
